### ISSUE TITLE
endless loop

### ISSUE THREAD

**Issue by niujixiao** [TNThieding/exif#14]
_parse_segments in _image.py line 35
no conditions for jumping out of the loop

**Comment by TNThieding** [comment]
Could you please clarify what the issue is with an example? Currently, the loop terminates once an EXIF segment prefix is found in the hexadecimal and the loop exits in all images I've tried out.

**Comment by niujixiao** [comment]
Some PNG images may cause the above problems.

**Comment by TNThieding** [comment]
I just released version 0.5.1 of the package (see #17) which breaks out of the loop and raises an exception once the entire hexadecimal string is traversed. Don't hesitate to follow-up with an additional issue if necessary.
