### ISSUE TITLE
Bug in _app1_metadata.py at line 103 (without side effects, for now...)

### ISSUE THREAD

**Issue by afaucon** [TNThieding/exif#18]
Instead of 
                tag_type = self._segment_hex.read(cursor, BYTES_PER_IFD_TAG_ID)
                cursor += BYTES_PER_IFD_TAG_TYPE
You should write
                tag_type = self._segment_hex.read(cursor, BYTES_PER_IFD_TAG_ID)
                cursor += BYTES_PER_IFD_TAG_ID

**Comment by TNThieding** [comment]
I just released version 0.8.2 of the package which addresses this issue. Don't hesitate to follow-up with an additional issue if necessary.
