### ISSUE TITLE
TypeError: super() argument 1 must be type, not classobj

### ISSUE THREAD

**Issue by evandrix** [TNThieding/exif#20]
```
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python2.7/site-packages/exif/_image.py", line 47, in __init__
    self._segments = {}
  File "/usr/local/lib/python2.7/site-packages/exif/_image.py", line 65, in __setattr__
    super(Image, self).__setattr__(key, value)
TypeError: super() argument 1 must be type, not classobj
```

**Comment by TNThieding** [comment]
What version of the package are you using? It looks like you're using Python 2, which is not supported in versions ``0.6.0`` and later.

**Comment by evandrix** [comment]
yeah Py 2.7, oh no wonder, ok

**Comment by axd1967** [comment]
in that case it should be specified on https://pypi.org/project/exif/ that Py2 is not supported .

I got the same problem, and undoubtedly more users will stumble across it.
