### ISSUE TITLE
'<unknown EXIF tag 40095>'

### ISSUE THREAD

**Issue by alamehor** [TNThieding/exif#22]
'<unknown EXIF tag 40091>',
 '<unknown EXIF tag 40094>',
 '<unknown EXIF tag 40095>',
 '_exif_ifd_pointer',

0x9c9b 	40091 	Image 	Exif.Image.XPTitle 	Byte 	Title tag used by Windows, encoded in UCS2
https://www.exiv2.org/tags.html

is possible to get image title

**Comment by TNThieding** [comment]
Hello, alamehor! Could you please share a sample image I could use to help validate and fix this use case?

**Comment by TNThieding** [comment]
I just released version 0.8.2 of the package which adds read-only support for these Windows XP style tags. Don't hesitate to follow-up with an additional issue if necessary.
