### ISSUE TITLE
Missing Title on Lightroom exported images (Windows)

### ISSUE THREAD

**Issue by marcolussetti** [TNThieding/exif#23]
Not sure if this is related to #22, but here it goes, along with attached image.

Flow:
- Set Title in Lightroom
- Export image from Adobe Lightroom on Windows
- Open image w/ Python 3.8+exit on Linux.

Result: missing title, but there is a "<unknown EXIF tag 36882>".

Will attach test image.

**Comment by marcolussetti** [comment]
![TEST_IMAGE_2](https://user-images.githubusercontent.com/15794684/75942580-9e50b600-5e47-11ea-96dd-ff5f5e0c4d33.jpg)

**Comment by marcolussetti** [comment]
This is the list of attributes I could extract:

```
_exif_ifd_pointer: 304
aperture_value: 4.970854
artist: TEST CREATOR
body_serial_number: 5006113
color_space: 1
contrast: 0
copyright: TEST COPYRIGHT
custom_rendered: 0
datetime: 2020:03:04 19:34:47
datetime_digitized: 2020:03:03 13:05:34
datetime_original: 2020:03:03 13:05:34
exposure_bias_value: 0.0
exposure_mode: 0
exposure_program: 3
exposure_time: 0.0025
f_number: 5.6
flash: 16
focal_length: 500.0
focal_length_in_35mm_film: 750
focal_plane_resolution_unit: 3
focal_plane_x_resolution: 2367.8104248046875
focal_plane_y_resolution: 2367.8104248046875
gain_control: 0
image_description: TEST CAPTION
lens_model: 200.0-500.0 mm f/5.6
lens_specification: (200.0, 500.0, 5.6, 5.6)
light_source: 0
make: NIKON CORPORATION
max_aperture_value: 5.0
metering_mode: 5
model: NIKON D7500
offset_time_digitized: -08:00
offset_time_original: -08:00
photographic_sensitivity: 400
recommended_exposure_index: 400
resolution_unit: 2
saturation: 0
scene_capture_type: 0
sensing_method: 2
sensitivity_type: 2
sharpness: 0
shutter_speed_value: 8.643856
software: Adobe Photoshop Lightroom Classic 9.1 (Windows)
subject_distance_range: 0
white_balance: 0
x_resolution: 240.0
y_resolution: 240.0
```

**Comment by TNThieding** [comment]
Marco,

Thank you for reaching out about this possible issue. After investigating the sample image, it appears that Lightroom is saving the title attribute in the XMP metadata section, a metadata format different from EXIF. I found this article explaining the differences: https://expertphotography.com/metadata-exif-iptc-xmp/

Is there a setting in Lightroom you can adjust to preserve the title in EXIF format?

Best regards,
Tyler Thieding

**Comment by marcolussetti** [comment]
Thank you for looking into this Tyler -- that makes a lot of sense, I was unaware of this :)

I will see if I can figure out if the EXIF title can be set from Lightroom, in case people ask in future.

And I will look into leveraging python-xmp-toolkit [1] if I can't configure Lightroom to behave nicely.

Thank you muchly -- will close this as well, not a bug :D

[1] https://github.com/python-xmp-toolkit/python-xmp-toolkit
