### ISSUE TITLE
enum34 seems to make it impossible to build a conda package

### ISSUE THREAD

**Issue by igorlopez** [TNThieding/exif#25]
Hi,

I have switched to using Anaconda (Ubuntu 18:04) and I cant build a conda package and it looks like the enum34 module is the culprit since the Python version is 3.7 and enum34 does not exist for Python 3.7.
Is it possible to use the pyton internal enum instead (exist since python 3.4).
Issue: [enum34 requirement](https://github.com/robshakir/pyangbind/issues/232) has a similar problem and I am not experienced enough to resolve this and I really need exif when running in my Anaconda installation.

**Comment by TNThieding** [comment]
Thank you for bringing this to my attention. I believe I fixed this issue in `v0.8.4` of the package, which I released minutes ago. If you still run into issues, feel free to open a new issue. Thank you!
