### ISSUE TITLE
Extract thumbnail from the exif metadata

### ISSUE THREAD

**Issue by moneer88** [TNThieding/exif#28]
Hi, 

I would like to ask you if there is any tag for thumbnail in EXIF data.

Regards

**Comment by TNThieding** [comment]
Thank you for the feature idea. I just added a thumbnail extraction function in `v0.9.0` of the package, which was released moments ago. You can now use ``get_thumbnail()`` to extract the bytes of a thumbnail image analogous to the package's ``get_file()`` function. Feel free to open another issue if you run into any trouble. Thanks!
