### ISSUE TITLE
Removing all know exif values

### ISSUE THREAD

**Issue by ArgiesDario** [TNThieding/exif#29]
Hey, great package 👍. I'm using it to remove all exif values and save a new file. I'm checking each attribute to be removed, and thought it would be usefull to have a method in your _image.py to erase all most common exif data, so anyone could just call that and get it clear for cases like mine.

Do you want me to do a Pull request with those changes?

Thank you!

**Comment by TNThieding** [comment]
That sounds like a good idea! I'd gladly welcome a pull request. Active development and CI/CD is through GitLab (at https://gitlab.com/TNThieding/exif/), so if you could submit the changes there it would be great. If you'd prefer to make the pull request on GitHub, you can do that too and I'll copy it into GitLab myself.

**Comment by ArgiesDario** [comment]
Sorry I do not have a GitLab account, it is much quicker to do it here for me. 
Pull request is sent

**Comment by TNThieding** [comment]
Thank you, @ArgiesDario. I'll continue our discussion on the pull request and I can move it to GitLab afterwards.

**Comment by TNThieding** [comment]
Released it in v0.11.0 of the package.
