### ISSUE TITLE
Image() Fails

### ISSUE THREAD

**Issue by pdr0663** [TNThieding/exif#5]
Thanks for this program, it will be very useful.

I'm using this under Python 3.7 on Windows 10.

 I can successfully open a file, but when it's passed to Image() an exception is raised. I have a large catalog of photos, mostly JPGs, and some of them cause an exception and some don't. I can't differentiate between those which produce an exception and those which don't. When I examine the excepted files in Windows, they seem normal, and have what looks like EXIF data (using the Properties->Details selection from the right-click menu).

Are there any known cases when an opened file will raise an exception?

Paul

**Comment by TNThieding** [comment]
Paul,

I did some preliminary debugging and it appears that images with EXIF data in little endian form raises exceptions. I am currently working on a fix and hope to have a patch delivered this weekend.

Best regards,
Tyler

**Comment by pdr0663** [comment]
Thanks Tyler, great response!

I guess there are several cases here:

1) File is not an image file (I pass all files and let your module deal with it)
2) File is an image file, but not supported
3) File is a supported image, but contains no EXIF data
4) Supported file with EXIF, but "endianism" different
5) Supported file with readable EXIF data

I'm new to Python, so what exception type is raised by your module upon these errors above? I couldn't seem to determine that. Is there an error object which can be queried using Python in an except: statement block?

Also, and I'm not sure it's a problem with your module, but I have many photos taken in Sydney Australia, who's location co-ordinates should be approx 33S, 151E. Without the directional specifiers, this should be -33, 151. When I read the EXIF data for these files, the latitude comes out as "33", which is 33N, not 33S, so the location is incorrect. Is there a "N" or "S" specifier in the raw EXIF data, and if so, is it possible that your module perhaps doesn't take this into account? I'm not sure it's a problem with the module, as it also seems that viewing the file properties in Windows gives the same results. If that's the case, then either my iPhone captured it poorly, or there's been some translation corruption in the file saving process from the phone to my PC. Anyway, can you please have a look?

Thanks again for your great work!

Paul

**Comment by pdr0663** [comment]
As an aside, I'm using your module to plow through my photos to find those taken at my father's place. I lost some photos of his workshop I want to find. Very useful. Also a good learning exercise for Python programming.

**Comment by TNThieding** [comment]
Paul,

I just released version 0.3.1 of the package (see #6), which improves little endian support and addresses the ``ValueError`` you previously received.

Regarding your 5 cases above, in the first three cases (i.e. if the file is not an image and/or it does not have EXIF data), an ``IOError`` is raised, stating "EXIF APP1 segment not found". With this new release, both case 4 and 5 should work as expected without raising exceptions.

Regarding your geotagging direction question, I did some investigating and it looks like the direction is stored in the ``gps_latitude_ref`` and ``gps_longitude_ref`` attributes.

Note that there are still known limitations and features I want to add to the package. See the documentation for a list of these. If there is functionality you need beyond what is currently offered, please feel free to contribute to the package!

Best regards,
Tyler
